# -*- coding: utf-8 -*-
"""decision_functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPKXENrUn4ShVSIEIA_IH9NqmcGMk8fO
"""

import joblib

best_threshold=joblib.load("best_business_threshold.pkl")

def assign_risk_band(probability):
  if probability<= 0.05:
    return "Low Risk"
  elif probability < best_threshold :
    return "Moderate Risk"
  elif probability < 0.30:
    return "High Risk"
  else:
    return "Critical Risk"

def assign_decision(risk_band):

  if risk_band=="Low Risk":
    return "Approve"
  elif risk_band in ["Moderate Risk","High Risk"]:
    return "Manual Review"
  else:
    return "Reject"